server:
  port: 7600
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7776/eureka/
zuul:
  routes:
    dm-user-consumer: /user/**  # /user/userlogin
    dm-xxxx-consumer: /xxxx/**
management:
  security:
    enabled: false
#  PreFilter:
#    pre:
#      disable: true