
server:
  port: 7776
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7777/eureka/
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
security:
  basic:
    enabled: true
  user:
    name: root
    password: 123456
spring:
  application:
    name: pee1